#include<stdio.h>
#include<stdlib.h>
#include<string.h>
#include<unistd.h>
#include<sys/types.h>
#include<sys/wait.h>
#include<sys/time.h>
#include<sys/resource.h>
#include<pthread.h>
#include<sys/stat.h>
#include<fcntl.h>
#include<sys/ioctl.h>
