//defines.h
#define OUTPUT 1
#define INPUT  0

#define SETBIT(WORD,BITPOS) 	WORD|=1<<BITPOS
#define READWRITEBIT(DWORD,DBIT,SWORD,SBIT) \
        DWORD=((DWORD&~(1<<DBIT))|(((SWORD>>SBIT)&1)<<DBIT))
#define READBIT(WORD,BITPOS) ((WORD>>BITPOS)&1)
#define READNIBBLE(WORD,BITPOS) ((WORD>>BITPOS)&0x0f)
#define WRITEBIT(WORD,BITPOS,BITLEVEL) \
        WORD=((WORD&~(1<<BITPOS))|(BITLEVEL<<BITPOS))
#define WRITENIBBLE(WORD,BITPOS,BITLEVEL) \
        WORD=((WORD&~(0x0f<<BITPOS))|(BITLEVEL<<BITPOS))
#define WRITEBYTE(WORD,BITPOS,BITLEVEL) WORD=((WORD&~(0xff<<BITPOS))|(BITLEVEL<<BITPOS))
