#define WRITEBYTE(WORD,BYTESTARTBITPOS,VAL)\
WORD=((WORD&~(0XFF<<BYTESTARTBITPOS))|((VAL<<BYTESTARTBITPOS)))
#define READWRITEBIT(DWORD,DBIT,SWORD,SBIT)\
                                            DWORD=((DWORD&~(1<<DBIT))|(((SWORD>>SBIT)&1)<<DBIT))
#define SETBIT(DWORD,DBIT) \
                            DWORD|=1<<DBIT 
#define READNIBBLE(WORD,BITPOS)  ((WORD>>BITPOS)&15)

#define WRITENIBBLE(WORD,BITPOS,VAL)  WORD=((WORD&~(0X0F<<BITPOS)) | (VAL<<BITPOS))

#define READBIT(WORD,BITPOS)   ((WORD>>BITPOS)&1)
