/* Main.c file generated by New Project wizard
 *
 * Created:   Tue Nov 11 2025
 * Processor: LPC2138
 * Compiler:  Keil for ARM
 */

#include <LPC2138.h>

int main (void)
 { 
   // Write your code here
   while (1)
      ;
   return 0;
 }   
